### ISSUE TITLE
Run start time not specifying AM/PM

### ISSUE THREAD

**Issue by diabWH3** [davegarred/WH3#14]
On trail list page; only for non-full day events.

**Comment by davegarred** [comment]
"AM" should show up for any events before noon, otherwise I've removed to minimize clutter. Seem legit?

**Comment by diabWH3** [comment]
I'd personally prefer having it listed always (or using 24-hour format),
but hashing before noon doesn't happen THAT often (except all winter for
Puget Sound).

**Comment by davegarred** [comment]
I like the 24 hour format thing but these kids...

Maybe put this in as an enhancement to allow time layout as setting.

**Comment by diabWH3** [comment]
I totally understand.
Not sure if we need a settings menu for just one setting that isn't super
important.

**Comment by davegarred** [comment]
Yeah, maybe excessive. Trying out in v0.0.8
