### ISSUE TITLE
Run number title lowercase

### ISSUE THREAD

**Issue by diabWH3** [davegarred/WH3#15]
Trail listing page: run number text is lowercase.
i.e. Sunday 4/28's Rain City trail.

**Comment by davegarred** [comment]
What are you thinking the preferred look for this is? First letter capitalized?

- Rain City H3 - Run #310
- Rain City H3  #310
- Rain City H3 - run: 310

**Comment by diabWH3** [comment]
First one seems to speak to my sensibilities (capital "R").

**Comment by davegarred** [comment]
corrected in v0.0.7
