### ISSUE TITLE
Add kennel "sponsor" to happy hours

### ISSUE THREAD

**Issue by davegarred** [davegarred/WH3#18]

**Comment by davegarred** [comment]
E.g., 

- Seattle H3 for Seattle Hashy Hour
- Puget Sound H3 for Renton Happy Hour

**Comment by diabWH3** [comment]
Need any calendar changes to implement this from my side?

**Comment by davegarred** [comment]
Negative, that's all client-side.

**Comment by davegarred** [comment]
E.g., 

- Seattle H3 for Seattle Hashy Hour
- Puget Sound H3 for Renton Happy Hour

**Comment by davegarred** [comment]
v0.0.8
