### ISSUE TITLE
Update or make kennel logos more consistent

### ISSUE THREAD

**Issue by diabWH3** [davegarred/WH3#3]
In trail detail page: Some kennel logos have empty space built into the file, causing odd spacing with the graphic and the trail title header.

DiaB can work to create consistent cropping on these files and email to FBS. Also, can work to source a full-color logo for HSWTF, get a logo for South Sound Shitshow H3, and possibly send a better option for the Rain City logo.

**Comment by davegarred** [comment]
These all are tolerable now (though that splash screen is still awful). 

Thanks DiaB!
