### ISSUE TITLE
Loading screen colors

### ISSUE THREAD

**Issue by diabWH3** [davegarred/WH3#8]
For the love of all that is unholy, please make the app loading screen the same green as the WA State map background. Baby blue and forest green do not go well together, especially with red text.

Just do something to not make it hurt my eyes so much! :)

**Comment by diabWH3** [comment]
The green background is definitely an improvement here! Probably good enough for now.

**Comment by davegarred** [comment]
Might be tolerable now.

(might be)

**Comment by diabWH3** [comment]
I like it, great change!
